# Verion of docker-compose to use
version: "3"

services:
  nginx:
    container_name: nginx_reverse_proxy
    restart: on-failure
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "8001:80"
    depends_on:
      - web
  web:
    container_name: api-app
    build: .
    restart: always
    command: gunicorn Billogram.wsgi --bind 0.0.0.0:8080
    env_file: api-app.env
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db
    ports:
      - "8000:8080"
  db:
    container_name: dev_db
    image: postgres:14.2-alpine
    env_file: database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  static_volume:
  postgres_data: